[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_sqlite", "php84Extensions.sqlite3", "php84Packages.composer", "nodejs_20"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build"]
