[provider]
name = "railway"

[build]
builder = "heroku/buildpacks:20"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && vendor/bin/heroku-php-apache2 public/"
